### ISSUE TITLE
exception during platformio upgrade

### ISSUE THREAD

**Issue by pelikhan** [ivankravets/platformio#45]
Here is the console output of the upgrade. There is an exception trace at the end. This was run from an administrative command prompt in Windows 8.1.

```
>platformio upgrade
There is a new version 0.10.1 of PlatformIO available.
Please upgrade it via platformio upgrade command.
Changes: http://docs.platformio.ikravets.com/en/latest/history.html

There are the new updates for platforms (atmelavr)
Please wait while updating platforms ...

Platform atmelavr
--------
Updating toolchain-atmelavr package:
Versions: Current=1, Latest=1    [Up-to-date]
Updating tool-avrdude package:
Versions: Current=1, Latest=1    [Up-to-date]
Updating framework-arduinoavr package:
Versions: Current=8, Latest=9    [Out-of-date]
Uninstalling framework-arduinoavr package:      [OK]
Installing framework-arduinoavr package:
Downloading  [####################################]  100%
Unpacking  [####################################]  100%

Platform timsp430
--------
Updating toolchain-timsp430 package:
Versions: Current=1, Latest=1    [Up-to-date]
Updating tool-mspdebug package:
Versions: Current=1, Latest=1    [Up-to-date]
Updating framework-energiamsp430 package:
Versions: Current=2, Latest=2    [Up-to-date]

Platform titiva
--------
Updating toolchain-gccarmnoneeabi package:
Versions: Current=1, Latest=1    [Up-to-date]
Updating tool-lm4flash package:
Versions: Current=1, Latest=1    [Up-to-date]
Updating framework-energiativa package:
Versions: Current=3, Latest=3    [Up-to-date]

There are the new updates for libraries (Adafruit-NeoPixel)
Please wait while updating libraries ...
Updating  [ 28 ] Adafruit-NeoPixel library:
Versions: Current=349b45afc9, Latest=61d5a3ebe9          [Out-of-date]
The library #28 'Adafruit-NeoPixel' has been successfully uninstalled!
Installing library [ 28 ]:
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
The library #28 'Adafruit-NeoPixel' has been successfully installed!

Downloading/unpacking platformio from https://pypi.python.org/packages/source/p/platformio/platformio-0.10.1.tar.gz#md5=65edff2e8a2c92906a847f7e55e71
8a8
  Downloading platformio-0.10.1.tar.gz
  Running setup.py (path:c:\users\....\appdata\local\temp\pip_build_jhalleux\platformio\setup.py) egg_info for package platformio

Requirement already up-to-date: click in c:\python27\lib\site-packages (from platformio)
Requirement already up-to-date: pyserial in c:\python27\lib\site-packages (from platformio)
Downloading/unpacking requests from https://pypi.python.org/packages/py2.py3/r/requests/requests-2.5.1-py2.py3-none-any.whl#md5=11dc91bc96c5c5e0b566c
e8f9c9644ab (from platformio)
Requirement already up-to-date: colorama in c:\python27\lib\site-packages (from platformio)
Installing collected packages: platformio, requests
  Found existing installation: platformio 0.9.2
    Uninstalling platformio:
      Successfully uninstalled platformio
  Running setup.py install for platformio

    Installing platformio-script.py script to C:\Python27\Scripts
    Installing platformio.exe script to C:\Python27\Scripts
Cleaning up...
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1443, in install
    requirement.commit_uninstall()
  File "C:\Python27\lib\site-packages\pip\req.py", line 610, in commit_uninstall
    self.uninstalled.commit()
  File "C:\Python27\lib\site-packages\pip\req.py", line 1860, in commit
    rmtree(self.save_dir)
  File "C:\Python27\lib\site-packages\pip\util.py", line 43, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27\lib\site-packages\pip\util.py", line 62, in rmtree_errorhandler
    func(path)
WindowsError: [Error 5] Access is denied: 'c:\\users\\....\\appdata\\local\\temp\\pip-p5rme5-uninstall\\python27\\scripts\\platformio.exe'

Storing debug log for failure in \pip.log
````

**Comment by ivankravets** [comment]
What is interesting, that PlatformIO is upgraded successfully and `pip` couldn't clean own `temp` dir. It looks strange for me. But I will fix it, because I also see this behaviour in my virtual machine.

Thanks.
